[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "strtool"
version = "0.1.0"
requires-python = ">=3.9"

dependencies = [
  "click>=8.0",
]

[project.scripts]
str = "strtool.cli:main"

[tool.ruff]
line-length = 140
