# https://github.com/starship/starship/discussions/1908

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[â®](bold green)"

[status]
disabled = false

[shell]
bash_indicator = "$"
zsh_indicator = "%"
xonsh_indicator = "ğŸš"
fish_indicator = "ğŸŸ"
powershell_indicator = "â¯_"
format = "$indicator(bold green) "
disabled = false

[custom.zsh]
symbol = "%"
when = '[ "$STARSHIP_SHELL" == "zsh" ]'
shell = ["bash", "--noprofile", "--norc"]

[custom.xonsh]
symbol = '\(ğŸ xsh\)'
when = '[ "$STARSHIP_SHELL" == "xonsh" ]'
shell = ["bash", "--noprofile", "--norc"]
